# hide titlebar if not tabbed
for_window [app_id="^.*"] border pixel 2

# move applications to workspaces
# for_window [app_id="LibreWolf"] move to workspace $ws2
for_window [class="steam"] move to workspace 5
for_window [app_id="vesktop"] move to workspace 4

for_window [app_id="thunar"] floating enable
for_window [title="Ignition"] floating enable
for_window [title="Ignition"] blur enable
for_window [title="Ignition"] border pixel 0
# for_window [title="Ignition"] blur_passes 3
# for_window [title="Ignition"] blur_radius 3
# for_window [app_id="vesktop"] blur enable
for_window [app_id="kitty"] blur enable
for_window [app_id="foot"] blur enable
for_window [app_id="dev.zed.Zed"] blur enable
for_window [app_id="flameshot"] floating enable

for_window [app_id="app"] floating enable

# for_window [title="^.*"] blur_passes 3
# for_window [title="^.*"] blur_radius 3

