# resize window (you can also use the mouse for that, but thats cringe)
mode "resize" {
    bindsym Left resize shrink width 10 px or 10 ppt
    bindsym Down resize grow height 10 px or 10 ppt
    bindsym Up resize shrink height 10 px or 10 ppt
    bindsym Right resize grow width 10 px or 10 ppt
    bindsym H resize shrink width 10 px or 10 ppt
    bindsym J resize grow height 10 px or 10 ppt
    bindsym K resize shrink height 10 px or 10 ppt
    bindsym L resize grow width 10 px or 10 ppt

    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

# or... make a power menu in waybar properly?
# mode "power" {
#     bindsym s exec ~/.config/sway/lock.sh, mode "default", exec loginctl suspend
#     bindsym l exec ~/.config/sway/lock.sh, mode "default"
#     bindsym $mod+h exec loginctl poweroff
#     bindsym $mod+r exec loginctl reboot

#     bindsym Escape mode "default"
#     bindsym Return mode "default"
#     bindsym $mod+p mode "default"
# }

# bindsym $mod+p mode "power"

