# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
    { on   = [ ".", "s" ], run  = "plugin what-size", desc = "Calc size of selection or cwd" },
    { on = "S", run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
    { on = "z", run = "plugin zoxide", desc = "jump to dir via zoxide" },
    { on = "d", run = "remove --permanently", desc = "Permanently delete selected files" },
]
